<?php
/**
 * ESG Framework Registry
 * Single source of truth for all supported reporting standards.
 * Add new frameworks here to make them available throughout the system.
 */

return [

    'BURSA_SEDG' => [
        'id'            => 'BURSA_SEDG',
        'name'          => 'Bursa Malaysia SEDG',
        'short'         => 'Bursa SEDG',
        'version'       => '2nd Edition (2022)',
        'description'   => 'The primary Malaysian ESG standard. Mandatory for Bursa Main Market and ACE Market listed companies.',
        'icon'          => 'bi-graph-up',
        'color'         => '#16a34a',
        'region'        => 'Malaysia',
        'category'      => 'malaysia',
        'category_label'=> 'Malaysian Standards',
        'mandatory_for' => 'Bursa Main Market & ACE Market listed companies',
        'best_for'      => 'All Malaysian companies targeting Bursa listing or investor ESG disclosure',
        'indicator_file'=> 'bursa_sedg',
        'indicators'    => 41,
        'badge'         => 'Recommended for Malaysia',
        'badge_color'   => 'success',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Required for all Malaysia green financing (BNM, CGC, SME Corp)',
    ],

    'GRI' => [
        'id'            => 'GRI',
        'name'          => 'GRI Standards',
        'short'         => 'GRI',
        'version'       => 'Universal Standards 2021',
        'description'   => 'The world\'s most widely used sustainability reporting standard. Used by 10,000+ companies in 100+ countries.',
        'icon'          => 'bi-globe',
        'color'         => '#0891b2',
        'region'        => 'Global',
        'category'      => 'international',
        'category_label'=> 'International Standards',
        'mandatory_for' => 'Voluntary globally; linked to Bursa SEDG and EU CSRD',
        'best_for'      => 'Companies with international investors, supply chains, or ESG ratings',
        'indicator_file'=> 'gri',
        'indicators'    => 33,
        'badge'         => 'Most Used Globally',
        'badge_color'   => 'info',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Accepted by most international ESG-linked financing',
    ],

    'ISSB' => [
        'id'            => 'ISSB',
        'name'          => 'ISSB / IFRS S1 & S2',
        'short'         => 'ISSB',
        'version'       => 'IFRS S1 & S2 (2023)',
        'description'   => 'New global baseline for sustainability and climate disclosure by IFRS Foundation. Bursa Malaysia is mandating adoption for large companies by 2025–2026.',
        'icon'          => 'bi-building-check',
        'color'         => '#7c3aed',
        'region'        => 'Global',
        'category'      => 'international',
        'category_label'=> 'International Standards',
        'mandatory_for' => 'Bursa large-cap companies (phased 2025–2026); G20 jurisdictions adopting',
        'best_for'      => 'Pre-IPO companies, large enterprises, companies seeking international investors',
        'indicator_file'=> 'issb',
        'indicators'    => 20,
        'badge'         => 'Bursa Mandating 2025–26',
        'badge_color'   => 'purple',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Required for ISSB-aligned green bonds and international financing',
    ],

    'TCFD' => [
        'id'            => 'TCFD',
        'name'          => 'TCFD Framework',
        'short'         => 'TCFD',
        'version'       => '2017 (absorbed into ISSB S2)',
        'description'   => 'Task Force on Climate-related Financial Disclosures. 4 pillars: Governance, Strategy, Risk Management, Metrics & Targets. Now the foundation of IFRS S2.',
        'icon'          => 'bi-thermometer-sun',
        'color'         => '#dc2626',
        'region'        => 'Global',
        'category'      => 'international',
        'category_label'=> 'International Standards',
        'mandatory_for' => 'Bursa listed companies (voluntary but strongly recommended); BNM for financial institutions',
        'best_for'      => 'Companies with climate-sensitive operations or seeking climate-focused investors',
        'indicator_file'=> 'tcfd',
        'indicators'    => 11,
        'badge'         => 'Climate Focused',
        'badge_color'   => 'danger',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Required for green bonds and climate-linked loans',
    ],

    'UN_SDGS' => [
        'id'            => 'UN_SDGS',
        'name'          => 'UN Sustainable Development Goals',
        'short'         => 'UN SDGs',
        'version'       => '2030 Agenda',
        'description'   => '17 global goals for sustainable development. Map your business activities to the SDGs most relevant to your industry.',
        'icon'          => 'bi-patch-check',
        'color'         => '#d97706',
        'region'        => 'Global',
        'category'      => 'international',
        'category_label'=> 'International Standards',
        'mandatory_for' => 'Voluntary; required for most government grants and development financing',
        'best_for'      => 'SME Corp grants, UNDP/UNIDO programs, impact investors, CSR reporting',
        'indicator_file'=> 'un_sdgs',
        'indicators'    => 17,
        'badge'         => 'Required for Grants',
        'badge_color'   => 'warning',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Required for SME Corp, UN, World Bank, ADB grant applications',
    ],

    'SASB_MANUFACTURING' => [
        'id'            => 'SASB_MANUFACTURING',
        'name'          => 'SASB — General Manufacturing',
        'short'         => 'SASB Mfg',
        'version'       => '2023 Edition',
        'description'   => 'Industry-specific ESG metrics for general manufacturing companies. Focused on material topics: emissions, energy, water, waste, safety, labour.',
        'icon'          => 'bi-gear',
        'color'         => '#64748b',
        'region'        => 'Global',
        'category'      => 'sasb',
        'category_label'=> 'SASB Industry Standards',
        'mandatory_for' => 'Voluntary; required by US/EU institutional investors using SASB for portfolio assessment',
        'best_for'      => 'Manufacturing companies exporting to US/EU or seeking international investment',
        'indicator_file'=> 'sasb_manufacturing',
        'indicators'    => 16,
        'badge'         => 'For Manufacturers',
        'badge_color'   => 'secondary',
        'supports_sasb_industry' => true,
        'financing_relevance' => 'Required for US institutional investor ESG questionnaires',
    ],

    'SASB_FOOD' => [
        'id'            => 'SASB_FOOD',
        'name'          => 'SASB — Food & Beverage',
        'short'         => 'SASB F&B',
        'version'       => '2023 Edition',
        'description'   => 'Industry-specific ESG metrics for food, beverage, and agri-food companies. Includes supply chain, packaging, food safety, water, and emissions.',
        'icon'          => 'bi-cup-hot',
        'color'         => '#f59e0b',
        'region'        => 'Global',
        'category'      => 'sasb',
        'category_label'=> 'SASB Industry Standards',
        'mandatory_for' => 'Voluntary; required by major F&B buyers (Nestlé, Unilever, IKEA supplier ESG audits)',
        'best_for'      => 'Food manufacturers, F&B exporters, halal industry players',
        'indicator_file'=> 'sasb_food',
        'indicators'    => 15,
        'badge'         => 'For F&B Companies',
        'badge_color'   => 'warning',
        'supports_sasb_industry' => true,
        'financing_relevance' => 'Required for Nestlé, Unilever, and major F&B supply chain audits',
    ],

    'SASB_TECH' => [
        'id'            => 'SASB_TECH',
        'name'          => 'SASB — Technology & Hardware',
        'short'         => 'SASB Tech',
        'version'       => '2023 Edition',
        'description'   => 'SASB metrics for technology hardware, electronics, and semiconductor companies. Covers supply chain, e-waste, data security, and emissions.',
        'icon'          => 'bi-cpu',
        'color'         => '#0891b2',
        'region'        => 'Global',
        'category'      => 'sasb',
        'category_label'=> 'SASB Industry Standards',
        'mandatory_for' => 'Voluntary; increasingly required by Apple, Dell, HP supply chain ESG programs',
        'best_for'      => 'Electronics manufacturers, semiconductor companies, tech exporters in Penang corridor',
        'indicator_file'=> 'sasb_tech',
        'indicators'    => 14,
        'badge'         => 'For Tech Companies',
        'badge_color'   => 'info',
        'supports_sasb_industry' => true,
        'financing_relevance' => 'Required for Apple, HP, Dell supplier ESG compliance',
    ],

    'CDP' => [
        'id'            => 'CDP',
        'name'          => 'CDP Climate Disclosure',
        'short'         => 'CDP',
        'version'       => '2024 Questionnaire',
        'description'   => 'The global standard for environmental disclosure. Major buyers (Apple, IKEA, Walmart, Sony) require suppliers to submit annual CDP questionnaires.',
        'icon'          => 'bi-cloud-sun',
        'color'         => '#0d9488',
        'region'        => 'Global',
        'category'      => 'supply_chain',
        'category_label'=> 'Supply Chain Standards',
        'mandatory_for' => 'Required by 280+ major corporations as part of supply chain engagement (CDP Supply Chain program)',
        'best_for'      => 'Exporters to MNCs, suppliers to Apple / IKEA / Walmart / Sony / BMW',
        'indicator_file'=> 'cdp',
        'indicators'    => 15,
        'badge'         => 'MNC Supply Chain',
        'badge_color'   => 'teal',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'CDP score used in MSCI and Sustainalytics ratings affecting institutional investment',
    ],

    'ESRS' => [
        'id'            => 'ESRS',
        'name'          => 'ESRS (EU CSRD)',
        'short'         => 'ESRS',
        'version'       => 'ESRS Set 1 (2023)',
        'description'   => 'European Sustainability Reporting Standards under the EU Corporate Sustainability Reporting Directive (CSRD). Mandatory for companies with significant EU business.',
        'icon'          => 'bi-flag',
        'color'         => '#1d4ed8',
        'region'        => 'European Union',
        'category'      => 'regional',
        'category_label'=> 'Regional Standards',
        'mandatory_for' => 'EU companies + non-EU companies with >€150M EU revenue or listed on EU exchange',
        'best_for'      => 'Malaysian exporters to EU, companies with EU customers or investors, EU supply chain participants',
        'indicator_file'=> 'esrs',
        'indicators'    => 22,
        'badge'         => 'EU Market Access',
        'badge_color'   => 'primary',
        'supports_sasb_industry' => false,
        'financing_relevance' => 'Required for EU Green Deal financing and EU market access from 2025',
    ],
];
