<?php
/**
 * Bursa Malaysia Sustainability Reporting Guide (SEDG) Indicators
 * Based on Bursa Malaysia Sustainability Reporting Guide 2nd Edition
 * and enhanced disclosure requirements for Main Market / ACE Market
 *
 * indicator_id   : unique code
 * category       : ENVIRONMENT | SOCIAL | GOVERNANCE
 * code           : display code
 * name           : indicator name
 * description    : what to disclose
 * unit           : measurement unit
 * data_type      : number | text | boolean | percentage | select
 * required       : true = mandatory, false = recommended
 * guidance       : how to collect/calculate
 * priority       : critical | high | medium | low (for gap analysis)
 * financing_link : relevant green financing benefit
 */

return [

    // =====================================================
    // ENVIRONMENT (E) — 13 Indicators
    // =====================================================
    'ENVIRONMENT' => [

        [
            'indicator_id' => 'SEDG-E01',
            'code'         => 'E-01',
            'name'         => 'Total Energy Consumption',
            'description'  => 'Total energy consumed by the organisation including electricity, fuel, and other energy sources.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Collect from TNB electricity bills + petrol/diesel receipts + piped gas invoices. Convert all to MWh (1 litre diesel ≈ 0.01 MWh).',
            'priority'     => 'critical',
            'financing_link' => 'Required for BNM Low Carbon Transition Facility',
        ],
        [
            'indicator_id' => 'SEDG-E02',
            'code'         => 'E-02',
            'name'         => 'Energy Intensity per Revenue',
            'description'  => 'Energy consumption relative to revenue (MWh per RM million of revenue).',
            'unit'         => 'MWh/RM million',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Divide total energy (MWh) by revenue in RM millions. Helps benchmark against industry peers.',
            'priority'     => 'medium',
            'financing_link' => 'Supports green loan eligibility assessment',
        ],
        [
            'indicator_id' => 'SEDG-E03',
            'code'         => 'E-03',
            'name'         => 'Renewable Energy Usage',
            'description'  => 'Total energy sourced from renewable sources (solar, hydro, biomass).',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Record solar generation from on-site panels + any green tariff electricity purchased from TNB.',
            'priority'     => 'medium',
            'financing_link' => 'Higher renewable % improves green financing rate',
        ],
        [
            'indicator_id' => 'SEDG-E04',
            'code'         => 'E-04',
            'name'         => 'Scope 1 GHG Emissions',
            'description'  => 'Direct greenhouse gas emissions from sources owned or controlled by the organisation (vehicles, boilers, generators).',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Calculate from: diesel/petrol consumption × emission factor. Use MyHIJAU emission factors or IPCC 2006 defaults.',
            'priority'     => 'critical',
            'financing_link' => 'Mandatory for carbon tax compliance from 2026',
        ],
        [
            'indicator_id' => 'SEDG-E05',
            'code'         => 'E-05',
            'name'         => 'Scope 2 GHG Emissions',
            'description'  => 'Indirect GHG emissions from purchased electricity, steam, heating or cooling.',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Multiply total kWh from TNB bills × Malaysia grid emission factor (0.694 tCO2e/MWh as of 2023).',
            'priority'     => 'critical',
            'financing_link' => 'Required for all green financing and carbon tax',
        ],
        [
            'indicator_id' => 'SEDG-E06',
            'code'         => 'E-06',
            'name'         => 'Scope 3 GHG Emissions',
            'description'  => 'All other indirect emissions in the value chain (business travel, supply chain, waste disposal).',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Focus on top 3 material categories: supplier emissions, logistics, and business travel. Use GHG Protocol Scope 3 standard.',
            'priority'     => 'high',
            'financing_link' => 'Required for supply chain sustainability certifications',
        ],
        [
            'indicator_id' => 'SEDG-E07',
            'code'         => 'E-07',
            'name'         => 'GHG Emission Intensity',
            'description'  => 'Total GHG emissions relative to revenue.',
            'unit'         => 'tCO2e/RM million',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Divide total Scope 1+2 emissions (tCO2e) by revenue in RM millions.',
            'priority'     => 'medium',
            'financing_link' => 'Used for benchmarking against industry peers',
        ],
        [
            'indicator_id' => 'SEDG-E08',
            'code'         => 'E-08',
            'name'         => 'Total Water Consumption',
            'description'  => 'Total volume of water withdrawn from all sources.',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Collect from SYABAS/SAJ/SAR water utility bills. 1,000 litres = 1 m³.',
            'priority'     => 'high',
            'financing_link' => 'Relevant for water-intensive manufacturing sectors',
        ],
        [
            'indicator_id' => 'SEDG-E09',
            'code'         => 'E-09',
            'name'         => 'Water Recycled or Reused',
            'description'  => 'Volume of water that was recycled or reused within operations.',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Track water reused in cooling systems, cleaning processes, or irrigation from internal recycling.',
            'priority'     => 'medium',
            'financing_link' => 'Demonstrates water efficiency for green certification',
        ],
        [
            'indicator_id' => 'SEDG-E10',
            'code'         => 'E-10',
            'name'         => 'Total Waste Generated',
            'description'  => 'Total mass of waste generated from operations.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Collect from licensed waste contractor weighing records. Include all solid waste types.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-E11',
            'code'         => 'E-11',
            'name'         => 'Hazardous Waste Generated',
            'description'  => 'Mass of hazardous waste generated (scheduled waste under EQA 1974).',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Record from DOE scheduled waste manifests (Jadual Sisa Buangan Kimia). Required by DOE Malaysia.',
            'priority'     => 'critical',
            'financing_link' => 'Regulatory compliance — DOE penalty risk if not tracked',
        ],
        [
            'indicator_id' => 'SEDG-E12',
            'code'         => 'E-12',
            'name'         => 'Non-Hazardous Waste Generated',
            'description'  => 'Mass of non-hazardous (general) waste generated.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Estimate from waste collection frequency × typical bin weight. Or use weighing records from local council.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-E13',
            'code'         => 'E-13',
            'name'         => 'Biodiversity Policy or Impact Description',
            'description'  => 'Description of significant biodiversity impacts and policy to manage them.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'State whether operations are near protected areas (Ramsar sites, Forest Reserves). Describe mitigation measures if applicable.',
            'priority'     => 'low',
            'financing_link' => null,
        ],
    ],

    // =====================================================
    // SOCIAL (S) — 15 Indicators
    // =====================================================
    'SOCIAL' => [

        [
            'indicator_id' => 'SEDG-S01',
            'code'         => 'S-01',
            'name'         => 'Total Number of Employees',
            'description'  => 'Total headcount of full-time and part-time employees at year end.',
            'unit'         => 'persons',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From payroll system or HR records. Include permanent + contract + part-time employees.',
            'priority'     => 'critical',
            'financing_link' => 'Required for all ESG disclosures and loan applications',
        ],
        [
            'indicator_id' => 'SEDG-S02',
            'code'         => 'S-02',
            'name'         => 'Number of New Employee Hires',
            'description'  => 'Total number of new employees hired during the reporting period.',
            'unit'         => 'persons',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Count from HR records. Include permanent hires only (exclude contractors/interns unless material).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-S03',
            'code'         => 'S-03',
            'name'         => 'Employee Turnover Rate',
            'description'  => 'Percentage of employees who left the organisation during the reporting period.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Formula: (Employees who left ÷ Average total employees) × 100. Industry benchmark for Malaysia SMEs: 15–25%.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-S04',
            'code'         => 'S-04',
            'name'         => '% Women in Total Workforce',
            'description'  => 'Percentage of total employees who are female.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'From HR records. Bursa target: 30% women in workforce. Malaysia average: 38%.',
            'priority'     => 'high',
            'financing_link' => 'Gender diversity KPI for CIMB/Maybank green loans',
        ],
        [
            'indicator_id' => 'SEDG-S05',
            'code'         => 'S-05',
            'name'         => '% Women in Management Positions',
            'description'  => 'Percentage of management-level employees who are female.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Count female managers, senior managers, and C-suite. Divide by total management headcount.',
            'priority'     => 'high',
            'financing_link' => 'Bursa 30% women in senior management target by 2025',
        ],
        [
            'indicator_id' => 'SEDG-S06',
            'code'         => 'S-06',
            'name'         => '% Women on Board of Directors',
            'description'  => 'Percentage of board members who are female.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Count female board directors ÷ total board members × 100. Bursa Main Market: min 30% target.',
            'priority'     => 'critical',
            'financing_link' => 'Bursa listing compliance requirement',
        ],
        [
            'indicator_id' => 'SEDG-S07',
            'code'         => 'S-07',
            'name'         => 'Work-Related Fatalities',
            'description'  => 'Number of work-related fatalities during the reporting period.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report from DOSH (JKKP) records. Any fatality must be reported to DOSH within 7 days under Occupational Safety and Health Act 1994.',
            'priority'     => 'critical',
            'financing_link' => 'DOSH compliance — high legal risk if not tracked',
        ],
        [
            'indicator_id' => 'SEDG-S08',
            'code'         => 'S-08',
            'name'         => 'Lost Time Injury Frequency Rate (LTIFR)',
            'description'  => 'Number of lost-time injuries per million hours worked.',
            'unit'         => 'per million hours',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Formula: (LTI incidents × 1,000,000) ÷ Total hours worked. Malaysia manufacturing benchmark: <5.0.',
            'priority'     => 'critical',
            'financing_link' => 'Required for insurance and OHS compliance',
        ],
        [
            'indicator_id' => 'SEDG-S09',
            'code'         => 'S-09',
            'name'         => 'Total Recordable Injury Rate (TRIR)',
            'description'  => 'Total recordable injuries per 200,000 hours worked.',
            'unit'         => 'per 200,000 hours',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Formula: (Total recordable injuries × 200,000) ÷ Total hours worked.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-S10',
            'code'         => 'S-10',
            'name'         => 'Average Training Hours per Employee',
            'description'  => 'Average number of training hours provided per employee per year.',
            'unit'         => 'hours/employee',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Total training hours across all employees ÷ average headcount. Include HRDF-claimable training.',
            'priority'     => 'high',
            'financing_link' => 'HRDF/HRD Corp tax deduction eligibility',
        ],
        [
            'indicator_id' => 'SEDG-S11',
            'code'         => 'S-11',
            'name'         => 'Total Training Investment',
            'description'  => 'Total amount invested in employee training and development.',
            'unit'         => 'RM',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'From finance records. Include HRDF levy + top-up spend. Show both total and per-employee spend.',
            'priority'     => 'medium',
            'financing_link' => 'HRD Corp grant eligibility',
        ],
        [
            'indicator_id' => 'SEDG-S12',
            'code'         => 'S-12',
            'name'         => 'Employee Engagement / Satisfaction Score',
            'description'  => 'Average employee satisfaction or engagement score from internal survey.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => false,
            'guidance'     => 'Conduct annual employee survey. Calculate % of employees who rate satisfaction ≥4/5 or ≥7/10.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-S13',
            'code'         => 'S-13',
            'name'         => 'Living Wage Compliance',
            'description'  => 'Whether all employees are paid at or above the national living wage.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => false,
            'guidance'     => 'Malaysia minimum wage: RM1,700/month (2023). Confirm all employees including contract workers meet this threshold.',
            'priority'     => 'high',
            'financing_link' => 'UFLPA compliance — required for US/EU export markets',
        ],
        [
            'indicator_id' => 'SEDG-S14',
            'code'         => 'S-14',
            'name'         => 'Parental Leave Policy',
            'description'  => 'Whether a formal parental leave policy is in place beyond minimum legal requirements.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Employment Act 1955: 98 days maternity leave. Policy should also cover paternity leave (min 3 days for private sector).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-S15',
            'code'         => 'S-15',
            'name'         => 'Community Investment Spend',
            'description'  => 'Total monetary contributions to community programs, CSR, or charitable causes.',
            'unit'         => 'RM',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Include cash donations, in-kind contributions (at market value), and staff volunteer hours (× market hourly rate).',
            'priority'     => 'low',
            'financing_link' => null,
        ],
    ],

    // =====================================================
    // GOVERNANCE (G) — 13 Indicators
    // =====================================================
    'GOVERNANCE' => [

        [
            'indicator_id' => 'SEDG-G01',
            'code'         => 'G-01',
            'name'         => 'Total Board Members',
            'description'  => 'Total number of directors on the board.',
            'unit'         => 'persons',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From latest company annual return (SSM). Include executive and non-executive directors.',
            'priority'     => 'critical',
            'financing_link' => 'Bursa listing compliance requirement',
        ],
        [
            'indicator_id' => 'SEDG-G02',
            'code'         => 'G-02',
            'name'         => '% Independent Directors on Board',
            'description'  => 'Percentage of board members who are independent non-executive directors.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Bursa Main Market: min 1/3 independent directors. ACE Market: same. Formula: Independent directors ÷ total board × 100.',
            'priority'     => 'critical',
            'financing_link' => 'Bursa listing compliance — mandatory for listed entities',
        ],
        [
            'indicator_id' => 'SEDG-G03',
            'code'         => 'G-03',
            'name'         => '% Women on Board',
            'description'  => 'Percentage of board seats held by women.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Bursa target: 30% women on board by 2025. No all-male boards allowed for listed companies from 2022.',
            'priority'     => 'critical',
            'financing_link' => 'Linked to gender diversity ESG score for financing',
        ],
        [
            'indicator_id' => 'SEDG-G04',
            'code'         => 'G-04',
            'name'         => 'ESG/Sustainability Committee Established',
            'description'  => 'Whether the board has established a dedicated ESG or sustainability committee.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Can be a standalone ESG committee or combined with Risk/Audit committee. Board must assign ESG oversight responsibility.',
            'priority'     => 'critical',
            'financing_link' => 'Required for pre-IPO Bursa compliance',
        ],
        [
            'indicator_id' => 'SEDG-G05',
            'code'         => 'G-05',
            'name'         => 'Anti-Corruption Policy',
            'description'  => 'Whether a formal anti-bribery and corruption (ABC) policy is in place.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'MACC Act 2009 Section 17A: Companies must have adequate procedures. Policy must cover gifts, hospitality, political donations.',
            'priority'     => 'critical',
            'financing_link' => 'Legal compliance — MACC corporate liability risk',
        ],
        [
            'indicator_id' => 'SEDG-G06',
            'code'         => 'G-06',
            'name'         => 'Whistleblower Policy',
            'description'  => 'Whether a formal whistleblower protection policy and channel is in place.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Whistleblower Protection Act 2010. Provide confidential reporting channel (hotline, email, or third-party platform).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-G07',
            'code'         => 'G-07',
            'name'         => 'Data Privacy / Personal Data Policy',
            'description'  => 'Whether a personal data protection policy compliant with PDPA 2010 is in place.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Personal Data Protection Act 2010 (PDPA). Must have privacy notice, consent mechanisms, and data breach response plan.',
            'priority'     => 'high',
            'financing_link' => 'Legal compliance — PDPA fine up to RM500,000',
        ],
        [
            'indicator_id' => 'SEDG-G08',
            'code'         => 'G-08',
            'name'         => 'Annual Sustainability / ESG Report Published',
            'description'  => 'Whether an annual sustainability or ESG report has been published.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Bursa Main Market: mandatory from 2023. ACE Market: mandatory from 2024. Standalone or integrated in Annual Report.',
            'priority'     => 'critical',
            'financing_link' => 'Required for Bursa listing compliance',
        ],
        [
            'indicator_id' => 'SEDG-G09',
            'code'         => 'G-09',
            'name'         => 'ESG Targets or KPIs Formally Set',
            'description'  => 'Whether formal ESG targets with measurable KPIs have been set and disclosed.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Set targets for at least: GHG reduction, energy efficiency, workforce diversity. Link to management KPIs.',
            'priority'     => 'high',
            'financing_link' => 'Sustainability-linked loan KPIs (SLL) require formal targets',
        ],
        [
            'indicator_id' => 'SEDG-G10',
            'code'         => 'G-10',
            'name'         => 'Supply Chain ESG Assessment Conducted',
            'description'  => 'Whether ESG assessment or due diligence has been conducted on key suppliers.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => false,
            'guidance'     => 'Screen top 10 suppliers by spend. Use self-assessment questionnaire or third-party audit. Critical for export markets.',
            'priority'     => 'high',
            'financing_link' => 'Required for EU CSRD supply chain compliance by 2025',
        ],
        [
            'indicator_id' => 'SEDG-G11',
            'code'         => 'G-11',
            'name'         => '% Employees Covered by Anti-Corruption Training',
            'description'  => 'Percentage of employees who received anti-corruption or ABC training.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => false,
            'guidance'     => 'Track from training records. MACC adequate procedures require periodic training. Minimum: annual training for high-risk roles.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SEDG-G12',
            'code'         => 'G-12',
            'name'         => 'Confirmed Corruption Incidents',
            'description'  => 'Number of confirmed incidents of corruption or bribery during the reporting period.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report confirmed incidents only (investigated and substantiated). Include actions taken (disciplinary, legal proceedings).',
            'priority'     => 'critical',
            'financing_link' => 'Zero tolerance required for all green financing',
        ],
        [
            'indicator_id' => 'SEDG-G13',
            'code'         => 'G-13',
            'name'         => 'Tax Strategy / Policy Published',
            'description'  => 'Whether a formal tax governance policy or strategy has been published.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => false,
            'guidance'     => 'Document tax risk management approach, transfer pricing policy, and commitment to tax compliance.',
            'priority'     => 'low',
            'financing_link' => null,
        ],
    ],
];
