<?php
/**
 * CDP Climate Change Questionnaire
 * Key disclosure areas from CDP 2024 Questionnaire
 * Used by 280+ major corporations for supply chain engagement
 *
 * Major CDP requesters in Malaysia supply chains:
 * Apple, IKEA, Walmart, Sony, BMW, Siemens, Schneider Electric, AstraZeneca
 */

return [

    'GOVERNANCE' => [

        [
            'indicator_id' => 'CDP-C1-1',
            'code'         => 'CDP-C1.1',
            'name'         => 'Board-level Oversight of Climate',
            'description'  => 'Is there board-level oversight of climate-related issues? Describe the governance structure.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Confirm whether the board or a board committee has explicit responsibility for climate. CDP requires naming the specific individual/committee and frequency of climate reporting to board.',
            'priority'     => 'critical',
            'financing_link' => 'CDP score affects MSCI ESG rating and investor access',
        ],
        [
            'indicator_id' => 'CDP-C1-2',
            'code'         => 'CDP-C1.2',
            'name'         => 'Management-level Climate Responsibility',
            'description'  => 'Who has management-level responsibility for climate-related issues?',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Name the job title and reporting line of the management owner for climate. If no dedicated CSO, name the CEO/COO who owns the climate agenda. CDP expects specific job title and name.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C11-2',
            'code'         => 'CDP-C11.2',
            'name'         => 'Internal Carbon Pricing',
            'description'  => 'Does the company use an internal price on carbon? If yes, what is the price?',
            'unit'         => 'USD/tCO2e',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Companies with internal carbon price receive higher CDP scores. Even a shadow price (not a real charge) of USD 20–50/tCO2e is acceptable. Document how it is used in investment appraisal.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
    ],

    'ENVIRONMENT' => [

        [
            'indicator_id' => 'CDP-C2-1',
            'code'         => 'CDP-C2.1',
            'name'         => 'Climate Risks and Opportunities Identified',
            'description'  => 'Have you identified any inherent climate-related risks that have potential to have a substantive financial or strategic impact on your business?',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'CDP requires listing specific climate risks with: risk type, timeframe (short/medium/long-term), likelihood, magnitude of impact, and management actions. Complete CDP\'s risk table format.',
            'priority'     => 'critical',
            'financing_link' => 'CDP score determines supply chain approval from Apple, IKEA, Walmart',
        ],
        [
            'indicator_id' => 'CDP-C3-1',
            'code'         => 'CDP-C3.1',
            'name'         => 'Climate Risks Integrated into Business Strategy',
            'description'  => 'Does your organisation\'s strategy account for climate-related risks and opportunities?',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Describe how climate scenarios have influenced your product strategy, capital allocation, and supply chain decisions. Provide a specific example of a climate-informed business decision.',
            'priority'     => 'critical',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C4-1',
            'code'         => 'CDP-C4.1',
            'name'         => 'GHG Reduction Targets',
            'description'  => 'Did you have an emissions target that was active in the reporting year?',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Companies with science-based targets (SBTi validated) score higher on CDP. If no formal target yet, describe your intention and timeline for setting one. CDP requires base year, target year, and % reduction.',
            'priority'     => 'critical',
            'financing_link' => 'SBTi target required for CDP A-List rating',
        ],
        [
            'indicator_id' => 'CDP-C4-2',
            'code'         => 'CDP-C4.2',
            'name'         => 'Performance Against Emissions Targets',
            'description'  => 'Performance against GHG emissions reduction targets in the reporting year.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Report actual % progress vs target: (Baseline emissions − Current emissions) ÷ Baseline × 100. Explain factors affecting performance (production changes, acquisitions, COVID, etc.).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C6-1',
            'code'         => 'CDP-C6.1',
            'name'         => 'Gross Scope 1 GHG Emissions',
            'description'  => 'Gross global Scope 1 emissions in metric tonnes CO2e.',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Use GHG Protocol Corporate Standard. CDP requires disclosing: total, biogenic CO2, verification status, and methodology. Use IPCC AR6 GWP values.',
            'priority'     => 'critical',
            'financing_link' => 'CDP disclosure required by 280+ major buying companies',
        ],
        [
            'indicator_id' => 'CDP-C6-3',
            'code'         => 'CDP-C6.3',
            'name'         => 'Gross Scope 2 GHG Emissions',
            'description'  => 'Gross global Scope 2 emissions — location-based and market-based.',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Location-based: TNB kWh × 0.694 kgCO2e/kWh. Market-based: adjust for RECs, PPAs, or green tariff. CDP requires BOTH figures separately.',
            'priority'     => 'critical',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C6-5',
            'code'         => 'CDP-C6.5',
            'name'         => 'Gross Scope 3 GHG Emissions',
            'description'  => 'Gross global Scope 3 emissions by relevant category.',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'CDP requires disclosing all relevant Scope 3 categories. Start with most material: Cat 1 (purchased goods), Cat 4 (upstream transport), Cat 11 (use of sold products), Cat 15 (investments).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C8-1',
            'code'         => 'CDP-C8.1',
            'name'         => 'Total Energy Consumption',
            'description'  => 'Total energy consumption from all sources within the organization\'s boundaries.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'CDP wants full energy breakdown: purchased electricity (MWh), self-generated electricity, fuel consumption (GJ converted to MWh). Include heat, steam, and cooling if applicable.',
            'priority'     => 'critical',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'CDP-C10-1',
            'code'         => 'CDP-C10.1',
            'name'         => 'GHG Emissions Verification / Assurance',
            'description'  => 'Has your Scope 1 and Scope 2 emissions data been externally verified?',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => false,
            'guidance'     => 'Third-party verification significantly improves CDP score (required for A-List). Use a certified GHG verifier (e.g. DNV, Bureau Veritas, SGS, SIRIM QAS). Level: Limited (preferred) or Reasonable assurance.',
            'priority'     => 'high',
            'financing_link' => 'CDP A-List requires verified emissions data',
        ],
    ],

    'SOCIAL' => [],
];
