<?php
/**
 * GRI Standards Indicators (Selected for SME relevance)
 * Based on GRI Universal Standards 2021 and Topic Standards
 * Curated for Malaysian SMEs, Consultants, and Pre-IPO companies
 */

return [

    // =====================================================
    // GRI 2 — General Disclosures (GOVERNANCE category)
    // =====================================================
    'GOVERNANCE' => [

        [
            'indicator_id' => 'GRI-2-01',
            'code'         => 'GRI 2-1',
            'name'         => 'Organizational Details',
            'description'  => 'Legal name, nature of ownership, HQ location, countries of operation, and scale of the organization.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'From SSM registration, company profile, and annual report. Include company registration number.',
            'priority'     => 'critical',
            'financing_link' => 'Foundation disclosure for all GRI reporting',
        ],
        [
            'indicator_id' => 'GRI-2-06',
            'code'         => 'GRI 2-6',
            'name'         => 'Activities, Value Chain, and Business Relationships',
            'description'  => 'Description of the organization\'s activities, value chain, and key business relationships.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Describe your products/services, key suppliers, distributors, and customers. Include supply chain map if available.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-2-12',
            'code'         => 'GRI 2-12',
            'name'         => 'Role of Highest Governance Body in ESG',
            'description'  => 'Role of the board or highest governance body in overseeing ESG impacts and strategy.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Describe how the board reviews and approves ESG strategy, targets, and performance. Include ESG committee charter if applicable.',
            'priority'     => 'critical',
            'financing_link' => 'Required for ESG-linked financing governance assessment',
        ],
        [
            'indicator_id' => 'GRI-2-26',
            'code'         => 'GRI 2-26',
            'name'         => 'Mechanisms for Seeking Advice and Raising Concerns',
            'description'  => 'Mechanisms for individuals to seek guidance on ethics and raise concerns about misconduct.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Describe your ethics hotline, whistleblower channel, grievance mechanism, and how complaints are handled.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-205-1',
            'code'         => 'GRI 205-1',
            'name'         => 'Anti-Corruption Risk Assessment',
            'description'  => 'Operations assessed for corruption risks and significant risks identified.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Conduct formal corruption risk assessment. Identify high-risk roles (procurement, sales, licensing). Document findings.',
            'priority'     => 'critical',
            'financing_link' => 'Legal compliance — MACC corporate liability',
        ],
        [
            'indicator_id' => 'GRI-205-2',
            'code'         => 'GRI 205-2',
            'name'         => 'Anti-Corruption Communication and Training',
            'description'  => '% of employees who received anti-corruption training, by category.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Track training completion from HR/LMS records. Separate: management vs non-management, high-risk vs standard roles.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-205-3',
            'code'         => 'GRI 205-3',
            'name'         => 'Confirmed Incidents of Corruption',
            'description'  => 'Number of confirmed incidents of corruption and actions taken.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report confirmed cases only. Include: employees dismissed, legal proceedings initiated, contracts terminated.',
            'priority'     => 'critical',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-206-1',
            'code'         => 'GRI 206-1',
            'name'         => 'Anti-Competitive Behaviour Legal Actions',
            'description'  => 'Legal actions pending or completed regarding anti-competitive behavior and violations of antitrust laws.',
            'unit'         => 'actions',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Report number of ongoing or completed legal actions. Include MyCC (Malaysia Competition Commission) proceedings.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
    ],

    // =====================================================
    // GRI 300 — ENVIRONMENTAL
    // =====================================================
    'ENVIRONMENT' => [

        [
            'indicator_id' => 'GRI-302-1',
            'code'         => 'GRI 302-1',
            'name'         => 'Energy Consumption Within the Organization',
            'description'  => 'Total energy consumed including non-renewable fuels, electricity, heating, and cooling.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Collect from TNB bills + fuel receipts + gas invoices. Apply GRI conversion factors. Separate renewable vs non-renewable.',
            'priority'     => 'critical',
            'financing_link' => 'Required for carbon tax baseline and green financing',
        ],
        [
            'indicator_id' => 'GRI-302-3',
            'code'         => 'GRI 302-3',
            'name'         => 'Energy Intensity',
            'description'  => 'Energy intensity ratio (energy consumption per unit of output or revenue).',
            'unit'         => 'MWh/RM million',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Choose industry-relevant denominator (revenue, production units, floor area). Be consistent year-over-year.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-302-4',
            'code'         => 'GRI 302-4',
            'name'         => 'Reduction in Energy Consumption',
            'description'  => 'Amount of reductions in energy consumption achieved as a direct result of conservation initiatives.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Compare actual vs baseline consumption. Document energy efficiency projects implemented (LED upgrades, VSD drives, etc.).',
            'priority'     => 'medium',
            'financing_link' => 'Demonstrates improvement for sustainability-linked loans',
        ],
        [
            'indicator_id' => 'GRI-303-3',
            'code'         => 'GRI 303-3',
            'name'         => 'Water Withdrawal by Source',
            'description'  => 'Total water withdrawal from all sources (surface water, groundwater, third-party).',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From utility bills (SYABAS, SAJ, SAR, SADA). Add borehole extraction if applicable. 1,000 litres = 1 m³.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-303-5',
            'code'         => 'GRI 303-5',
            'name'         => 'Water Consumption',
            'description'  => 'Total water consumption (withdrawal minus discharge).',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Water consumption = total withdrawal − total discharge. For SMEs without discharge measurement, use total withdrawal as proxy.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-305-1',
            'code'         => 'GRI 305-1',
            'name'         => 'Scope 1 GHG Emissions',
            'description'  => 'Direct GHG emissions from owned or controlled sources (tCO2e).',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Stationary combustion (generators, boilers) + mobile combustion (vehicles). Use IPCC AR5 GWP values.',
            'priority'     => 'critical',
            'financing_link' => 'Carbon tax baseline — mandatory from 2026',
        ],
        [
            'indicator_id' => 'GRI-305-2',
            'code'         => 'GRI 305-2',
            'name'         => 'Scope 2 GHG Emissions',
            'description'  => 'Indirect GHG emissions from purchased electricity and energy (tCO2e).',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Multiply total kWh × Malaysia grid emission factor (0.694 kgCO2e/kWh). Use location-based method for reporting.',
            'priority'     => 'critical',
            'financing_link' => 'Carbon tax and green financing baseline',
        ],
        [
            'indicator_id' => 'GRI-305-3',
            'code'         => 'GRI 305-3',
            'name'         => 'Scope 3 GHG Emissions',
            'description'  => 'All other indirect emissions in the value chain (supply chain, logistics, business travel).',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Start with material categories: Cat 1 (purchased goods), Cat 4 (upstream transport), Cat 6 (business travel).',
            'priority'     => 'high',
            'financing_link' => 'Required for EU CBAM and supply chain sustainability',
        ],
        [
            'indicator_id' => 'GRI-305-4',
            'code'         => 'GRI 305-4',
            'name'         => 'GHG Emissions Intensity',
            'description'  => 'GHG emissions intensity ratio relative to a chosen denominator.',
            'unit'         => 'tCO2e/RM million',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Total Scope 1+2 emissions ÷ revenue in RM millions. Allows year-over-year comparison despite revenue changes.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-306-3',
            'code'         => 'GRI 306-3',
            'name'         => 'Waste Generated',
            'description'  => 'Total weight of waste generated, broken down by hazardous and non-hazardous.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From licensed waste contractor records + DOE scheduled waste manifests. Separate hazardous from general waste.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-306-4',
            'code'         => 'GRI 306-4',
            'name'         => 'Waste Diverted from Disposal',
            'description'  => 'Total weight of waste diverted from disposal through recycling, composting, or reuse.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Track from recycling contractor purchase orders or waste records. Include materials sold to scrap dealers.',
            'priority'     => 'medium',
            'financing_link' => 'Demonstrates circular economy progress',
        ],
        [
            'indicator_id' => 'GRI-306-5',
            'code'         => 'GRI 306-5',
            'name'         => 'Waste Directed to Disposal',
            'description'  => 'Total weight of waste sent to landfill, incineration, or other disposal methods.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'From waste contractor disposal certificates. Separate landfill from incineration from treatment.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-304-1',
            'code'         => 'GRI 304-1',
            'name'         => 'Operations Near Protected Areas (Biodiversity)',
            'description'  => 'Operational sites owned, leased, or managed in or near protected areas or areas of high biodiversity value.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Check proximity to Ramsar sites, Forest Reserves, National Parks. If none, state "No operations near protected areas".',
            'priority'     => 'low',
            'financing_link' => null,
        ],
    ],

    // =====================================================
    // GRI 400 — SOCIAL
    // =====================================================
    'SOCIAL' => [

        [
            'indicator_id' => 'GRI-401-1',
            'code'         => 'GRI 401-1',
            'name'         => 'New Employee Hires and Employee Turnover',
            'description'  => 'Total number and rate of new hires and employee turnover by age group, gender, and region.',
            'unit'         => 'persons',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Breakdown new hires and exits by: gender (M/F), age group (<30, 30–50, >50), employment type. Calculate turnover rate.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-401-3',
            'code'         => 'GRI 401-3',
            'name'         => 'Parental Leave',
            'description'  => 'Total employees entitled to parental leave, those who took it, and return-to-work rate.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => false,
            'guidance'     => 'Track maternity and paternity leave separately. Calculate return-to-work rate: employees who returned ÷ employees who took leave.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-403-2',
            'code'         => 'GRI 403-2',
            'name'         => 'Hazard Identification and Risk Assessment (OHS)',
            'description'  => 'Whether a formal hazard identification, risk assessment, and incident investigation process is in place.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Document your HIRARC (Hazard Identification, Risk Assessment, Risk Control) process. Required under OSH Act 1994.',
            'priority'     => 'critical',
            'financing_link' => 'DOSH compliance — legal requirement',
        ],
        [
            'indicator_id' => 'GRI-403-9',
            'code'         => 'GRI 403-9',
            'name'         => 'Work-Related Injuries',
            'description'  => 'Work-related injuries including fatalities, high-consequence injuries, and LTIFR.',
            'unit'         => 'per million hours',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report LTIFR: (LTI × 1,000,000) ÷ hours worked. Report separately for employees and contractors.',
            'priority'     => 'critical',
            'financing_link' => 'OHS insurance compliance',
        ],
        [
            'indicator_id' => 'GRI-404-1',
            'code'         => 'GRI 404-1',
            'name'         => 'Average Training Hours per Employee',
            'description'  => 'Average hours of training per employee per year, by gender and employee category.',
            'unit'         => 'hours/employee',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Total training hours ÷ average headcount. Separate by manager vs non-manager, male vs female.',
            'priority'     => 'high',
            'financing_link' => 'HRD Corp / HRDF training grant eligibility',
        ],
        [
            'indicator_id' => 'GRI-404-2',
            'code'         => 'GRI 404-2',
            'name'         => 'Programs for Upgrading Employee Skills',
            'description'  => 'Programs for upgrading employee skills and transition assistance programs.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Describe training programs, professional certifications supported, digital upskilling initiatives, and succession planning.',
            'priority'     => 'medium',
            'financing_link' => 'HRDC/HRD Corp SBL-Khas grant eligible programs',
        ],
        [
            'indicator_id' => 'GRI-405-1',
            'code'         => 'GRI 405-1',
            'name'         => 'Diversity of Governance Bodies and Employees',
            'description'  => '% women and age group breakdown across board, management, and total workforce.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Provide breakdowns for: Board (gender, age), Senior management (gender, age), Total employees (gender, age group).',
            'priority'     => 'critical',
            'financing_link' => 'Gender KPI for diversity-linked financing',
        ],
        [
            'indicator_id' => 'GRI-406-1',
            'code'         => 'GRI 406-1',
            'name'         => 'Incidents of Discrimination',
            'description'  => 'Total number of incidents of discrimination and corrective actions taken.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Track from HR grievance records. Include discrimination complaints by type (gender, race, religion, disability). Report actions taken.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'GRI-407-1',
            'code'         => 'GRI 407-1',
            'name'         => 'Freedom of Association and Collective Bargaining',
            'description'  => 'Operations where right to freedom of association or collective bargaining may be at risk.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Industrial Relations Act 1967: Rights to form/join trade unions. State whether any operations restrict these rights.',
            'priority'     => 'high',
            'financing_link' => 'UFLPA compliance for US export markets',
        ],
        [
            'indicator_id' => 'GRI-408-1',
            'code'         => 'GRI 408-1',
            'name'         => 'Operations at Risk of Child Labour',
            'description'  => 'Operations and suppliers at significant risk for incidents of child labour.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Children and Young Persons (Employment) Act 1966: No employment of children below 15. Confirm compliance and supply chain assessment.',
            'priority'     => 'critical',
            'financing_link' => 'Required for EU, US market access',
        ],
        [
            'indicator_id' => 'GRI-409-1',
            'code'         => 'GRI 409-1',
            'name'         => 'Operations at Risk of Forced or Compulsory Labour',
            'description'  => 'Operations and suppliers at significant risk for incidents of forced or compulsory labour.',
            'unit'         => null,
            'data_type'    => 'boolean',
            'required'     => true,
            'guidance'     => 'Anti-Trafficking in Persons Act 2007. Forced labour indicators: passport confiscation, wage deductions, restricted movement. Must conduct worker interviews.',
            'priority'     => 'critical',
            'financing_link' => 'UFLPA — US import ban risk if non-compliant',
        ],
    ],
];
