<?php
/**
 * SASB — Industrial Machinery & Goods (General Manufacturing)
 * Based on SASB RT-IG Standard (2023)
 * Covers: general manufacturers, machinery, electronics assembly, plastics, rubber
 *
 * For Malaysia: Most relevant to Selangor/Penang manufacturing corridor,
 * Export-oriented manufacturers (EOM), FTZ companies
 */

return [

    'ENVIRONMENT' => [

        [
            'indicator_id' => 'SASB-MFG-E01',
            'code'         => 'RT-IG-130a.1',
            'name'         => 'Total Energy Consumed',
            'description'  => 'Total energy consumed and % from grid electricity, % from renewables.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From TNB bills + fuel receipts. Calculate % renewable if solar installed. SASB wants breakdown: grid electricity vs self-generated vs purchased renewable.',
            'priority'     => 'critical',
            'financing_link' => 'Required for US institutional investor ESG scoring',
        ],
        [
            'indicator_id' => 'SASB-MFG-E02',
            'code'         => 'RT-IG-130a.2',
            'name'         => 'Scope 1 and 2 GHG Emissions',
            'description'  => 'Gross Scope 1 emissions and Scope 2 emissions.',
            'unit'         => 'tCO2e',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Same as Bursa E-04 and E-05. Use Malaysia grid factor 0.694 kgCO2e/kWh for Scope 2. Disclose separately; SASB requires both disclosed.',
            'priority'     => 'critical',
            'financing_link' => 'Carbon tax compliance and supply chain disclosure',
        ],
        [
            'indicator_id' => 'SASB-MFG-E03',
            'code'         => 'RT-IG-150a.1',
            'name'         => 'Water Withdrawn in Water-Stressed Areas',
            'description'  => 'Total water withdrawn and % in water-stressed regions.',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Total from utility bills. Check WRI Aqueduct to see if your facility is in a water-stressed area. Klang Valley and some Kedah/Penang areas are medium-high stress.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-MFG-E04',
            'code'         => 'RT-IG-150a.2',
            'name'         => 'Incidents of Non-Compliance with Water Quality Standards',
            'description'  => 'Number of incidents of non-compliance with water quality regulations.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From DOE compliance records. Include effluent discharge violations, Environmental Quality (Industrial Effluent) Regulations 2009 breaches.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-MFG-E05',
            'code'         => 'RT-IG-150b.1',
            'name'         => 'Hazardous Waste Generated',
            'description'  => 'Total amount of hazardous waste generated and disposed by treatment type.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'From DOE scheduled waste manifests. Separate by disposal method: incineration, recovery, landfill. Key for US investors due to RCRA reporting parallels.',
            'priority'     => 'critical',
            'financing_link' => 'DOE regulatory compliance — fine risk if not tracked',
        ],
        [
            'indicator_id' => 'SASB-MFG-E06',
            'code'         => 'RT-IG-160a.1',
            'name'         => 'Air Quality — NOx, SOx, VOC Emissions',
            'description'  => 'Air pollutant emissions: NOx, SOx, volatile organic compounds (VOCs), and particulate matter.',
            'unit'         => 'metric tonnes',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'From stack emission monitoring reports (if applicable). DOE requires stack monitoring for scheduled premises. Relevant for paint, chemical, and heavy manufacturing.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
    ],

    'SOCIAL' => [

        [
            'indicator_id' => 'SASB-MFG-S01',
            'code'         => 'RT-IG-320a.1',
            'name'         => 'Total Recordable Incident Rate (TRIR)',
            'description'  => 'Total recordable incident rate (TRIR) and fatality rate for full-time employees and contract workers.',
            'unit'         => 'per 200,000 hours',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Formula: (Total recordable incidents × 200,000) ÷ total hours worked. Disclose separately for direct employees and contractors. US manufacturing benchmark: <2.5.',
            'priority'     => 'critical',
            'financing_link' => 'OHS compliance and insurance premium linked',
        ],
        [
            'indicator_id' => 'SASB-MFG-S02',
            'code'         => 'RT-IG-320a.2',
            'name'         => 'Description of OHS Management System',
            'description'  => 'Description of safety management system and OHSAS 18001 / ISO 45001 certification status.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Describe HIRARC process, near-miss reporting system, safety committees, ISO 45001 certification status. SASB investors want to know if system is certified and audited.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-MFG-S03',
            'code'         => 'RT-IG-330a.1',
            'name'         => 'Supply Chain Human Rights Assessment',
            'description'  => 'Description of the process to identify and address human rights risks in the supply chain.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Describe supplier screening process for: forced labour, child labour, unsafe working conditions. Include top supplier countries assessed. Reference RBA (Responsible Business Alliance) Code if applicable.',
            'priority'     => 'critical',
            'financing_link' => 'UFLPA — US import ban risk for non-compliant supply chains',
        ],
        [
            'indicator_id' => 'SASB-MFG-S04',
            'code'         => 'RT-IG-330a.2',
            'name'         => 'Tier 1 Supplier Social Audit Rate',
            'description'  => 'Percentage of Tier 1 suppliers audited against a social and labour standard.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => false,
            'guidance'     => 'Count % of significant Tier 1 suppliers (by spend) who have been audited using SMETA, BSCI, or equivalent social audit standard in the last 2 years.',
            'priority'     => 'high',
            'financing_link' => 'Required for Walmart, Target, H&M supply chain programs',
        ],
    ],

    'GOVERNANCE' => [

        [
            'indicator_id' => 'SASB-MFG-G01',
            'code'         => 'RT-IG-510a.1',
            'name'         => 'Transparency and Product Labelling',
            'description'  => 'Description of practices for informing customers about product composition, materials origin, and hazardous content.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Describe compliance with labelling regulations: REACH (EU), RoHS, Conflict Minerals (Dodd-Frank 1502 for tin, tantalum, tungsten, gold). Relevant for electronics and component manufacturers.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-MFG-G02',
            'code'         => 'RT-IG-510b.1',
            'name'         => 'Sustainability Integration in Product Design',
            'description'  => 'Description of how sustainability considerations are integrated into product design and lifecycle assessment.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Describe eco-design practices: design for recyclability, reduced material use, extended product lifespan. Include % of products with lifecycle assessment (LCA) completed.',
            'priority'     => 'medium',
            'financing_link' => 'EU Ecodesign Regulation compliance for EU market access',
        ],
        [
            'indicator_id' => 'SASB-MFG-G03',
            'code'         => 'RT-IG-520a.1',
            'name'         => 'Materials Sourcing — Responsible Minerals',
            'description'  => 'Description of due diligence practices to identify and manage risks in the mineral supply chain.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'If using tin, tantalum, tungsten, gold (3TG) — describe conflict minerals due diligence per OECD Guidance. Applies to electronics, PCB, and component manufacturers.',
            'priority'     => 'low',
            'financing_link' => null,
        ],
    ],
];
