<?php
/**
 * SASB — Food & Beverage Processing (FB-PF)
 * Based on SASB FB-PF Standard (2023)
 * Covers: food manufacturers, beverage companies, halal food processors,
 * palm oil downstream, dairy, snack foods, ready meals
 */

return [

    'ENVIRONMENT' => [
        [
            'indicator_id' => 'SASB-FB-E01',
            'code'         => 'FB-PF-130a.1',
            'name'         => 'Total Energy Consumed (F&B)',
            'description'  => 'Total energy consumed and % from renewables. Include process heat (steam, boiler) and refrigeration loads.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'F&B facilities typically have high energy intensity for cooling, cooking, and steam. Collect TNB bills + fuel (LPG, natural gas) + diesel. Calculate renewable % from solar if installed.',
            'priority'     => 'critical',
            'financing_link' => 'BNM Low Carbon Transition Facility for agri-food sector',
        ],
        [
            'indicator_id' => 'SASB-FB-E02',
            'code'         => 'FB-PF-140a.1',
            'name'         => 'Total Water Withdrawn',
            'description'  => 'Total water withdrawn and % in water-stressed regions.',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'F&B is water-intensive. Include process water, boiler water, cleaning water. Collect from SYABAS/SAJ bills. Water efficiency is key differentiator for buyers like Nestlé and Unilever.',
            'priority'     => 'critical',
            'financing_link' => 'Nestlé/Unilever water stewardship KPI for supplier approval',
        ],
        [
            'indicator_id' => 'SASB-FB-E03',
            'code'         => 'FB-PF-150a.1',
            'name'         => 'Food Loss and Waste',
            'description'  => 'Total weight of food loss and waste and % recovered (composting, animal feed, biogas).',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Track food waste from production, trimming, rejects, and expiry. Measure recovery rate: sent to composting, animal feed, or biogas. UN SDG 12.3 target: halve food waste by 2030.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-FB-E04',
            'code'         => 'FB-PF-160a.1',
            'name'         => 'Packaging Materials Used',
            'description'  => 'Total weight of packaging and % that is recyclable, compostable, or reusable.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Measure primary, secondary, and tertiary packaging weight. Calculate % recyclable or compostable. EU Single Use Plastics Directive is increasingly influencing buyer requirements globally.',
            'priority'     => 'high',
            'financing_link' => 'EU Single Use Plastics compliance for EU export market',
        ],
        [
            'indicator_id' => 'SASB-FB-E05',
            'code'         => 'FB-PF-430a.1',
            'name'         => 'Ingredient Sourcing — Sustainability Certifications',
            'description'  => '% of ingredients/raw materials certified to a sustainability standard (RSPO, Rainforest Alliance, MSPO, organic, UTZ).',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'For palm oil: MSPO (Malaysian Sustainable Palm Oil) or RSPO certification %. For coffee, cocoa: Rainforest Alliance or Fairtrade. Key for Nestlé, Unilever, Kraft Heinz supplier approval.',
            'priority'     => 'critical',
            'financing_link' => 'RSPO/MSPO certification reduces EU market access risk under EUDR',
        ],
    ],

    'SOCIAL' => [
        [
            'indicator_id' => 'SASB-FB-S01',
            'code'         => 'FB-PF-250a.1',
            'name'         => 'Nutritional Improvement Targets',
            'description'  => 'Description of targets and progress to reformulate products to improve nutritional profile.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Describe: sodium/sugar reduction targets, whole grain inclusion, fortification programs. Reference Malaysia\'s Healthier Choice Logo (HCL) and MOH nutrition standards. Relevant for public health SDG 3.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-FB-S02',
            'code'         => 'FB-PF-260a.1',
            'name'         => 'Food Safety Incidents',
            'description'  => 'Number of recalls and percentage of revenue affected by product recalls related to food safety.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report product recalls initiated during reporting period. Include FDA (US), EFSA (EU), or MOH Malaysia product recalls. Describe corrective actions and root cause investigation.',
            'priority'     => 'critical',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-FB-S03',
            'code'         => 'FB-PF-430b.1',
            'name'         => 'Supplier Audit Rate for Ethical Sourcing',
            'description'  => '% of suppliers verified to meet ethical sourcing standards (labour rights, environmental standards).',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'Count % of significant suppliers (by spend) with social audit (SMETA/BSCI) in last 2 years. Critical for palm oil, rubber gloves, and plantation supply chains.',
            'priority'     => 'critical',
            'financing_link' => 'Required by Nestlé, Unilever, Mondelēz supplier codes',
        ],
    ],

    'GOVERNANCE' => [
        [
            'indicator_id' => 'SASB-FB-G01',
            'code'         => 'FB-PF-270a.1',
            'name'         => 'Marketing Practices for Children',
            'description'  => 'Revenue from products with marketing restrictions due to nutritional content, and compliance with marketing codes for children.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => false,
            'guidance'     => 'Describe compliance with Malaysia\'s Food Act regulations on marketing to children. Relevant for snack foods, cereals, beverages. Reference WHO/UNICEF marketing code compliance.',
            'priority'     => 'low',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-FB-G02',
            'code'         => 'FB-PF-430a.2',
            'name'         => 'Priority Sourcing Regions and Deforestation Risk',
            'description'  => 'Description of sourcing regions and processes to manage deforestation and land conversion risk.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'State key sourcing regions for major raw materials. Describe no-deforestation commitment, EUDR compliance readiness, traceability to plantation (mill level vs plantation level). CRITICAL for palm oil, soy, cocoa.',
            'priority'     => 'critical',
            'financing_link' => 'EU Deforestation Regulation (EUDR) — EU market access at risk from 2025',
        ],
    ],
];
