<?php
/**
 * SASB — Technology Hardware & Electronic Equipment (TC-HW)
 * Based on SASB TC-HW Standard (2023)
 * Covers: electronics manufacturers, PCB assembly, semiconductor, EEE assembly,
 * component manufacturers (Penang, Johor, Selangor free trade zones)
 */

return [

    'ENVIRONMENT' => [
        [
            'indicator_id' => 'SASB-TECH-E01',
            'code'         => 'TC-HW-130a.1',
            'name'         => 'Total Energy Consumed (Tech)',
            'description'  => 'Total energy consumed and % from grid, % from renewables. Include cleanroom HVAC loads.',
            'unit'         => 'MWh',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Electronics fabs and cleanrooms are energy-intensive. Collect TNB bills + backup power (UPS/diesel). Track renewable energy from on-site solar or green tariff. Apple/HP require this data.',
            'priority'     => 'critical',
            'financing_link' => 'Apple Supplier Clean Energy Program — renewable energy requirements',
        ],
        [
            'indicator_id' => 'SASB-TECH-E02',
            'code'         => 'TC-HW-150a.1',
            'name'         => 'Water Consumption (Tech)',
            'description'  => 'Total water withdrawn and % in water-stressed regions.',
            'unit'         => 'm³',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Semiconductor and PCB cleaning uses significant water. Measure from utility bills and track ultra-pure water (UPW) consumption separately if applicable.',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-TECH-E03',
            'code'         => 'TC-HW-150b.1',
            'name'         => 'E-Waste and End-of-Life Product Management',
            'description'  => 'Amount of products accepted for take-back and weight of products and materials reused, recycled, or landfilled.',
            'unit'         => 'tonnes',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Track production scrap + end-of-life product recovery. EU WEEE Directive applies to EU exports. Describe take-back programs and certified e-waste recyclers (under DOE Malaysia).',
            'priority'     => 'high',
            'financing_link' => 'EU WEEE compliance for EU market access',
        ],
        [
            'indicator_id' => 'SASB-TECH-E04',
            'code'         => 'TC-HW-160a.1',
            'name'         => 'Hazardous Chemical Use and Emissions',
            'description'  => 'Description of processes for managing hazardous chemical use, including substitution and reduction programs.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'List key hazardous chemicals used (solvents, flux, acids, plating chemicals). Describe REACH compliance for EU exports, RoHS compliance for restricted substances. DOE scheduled chemical management.',
            'priority'     => 'critical',
            'financing_link' => 'EU RoHS and REACH compliance — mandatory for EU market',
        ],
    ],

    'SOCIAL' => [
        [
            'indicator_id' => 'SASB-TECH-S01',
            'code'         => 'TC-HW-320a.1',
            'name'         => 'OHS Incident Rate (Tech)',
            'description'  => 'TRIR and fatality rate for employees and contractors. Include ergonomics-related illnesses.',
            'unit'         => 'per 200,000 hours',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Electronics workers face ergonomic risks (repetitive strain) and chemical exposure risks. Report total recordable incidents including occupational illness. Apple/HP require TRIR below 1.0.',
            'priority'     => 'critical',
            'financing_link' => 'Apple/HP supplier code compliance requirement',
        ],
        [
            'indicator_id' => 'SASB-TECH-S02',
            'code'         => 'TC-HW-430a.1',
            'name'         => 'Conflict Minerals Sourcing',
            'description'  => 'Description of the process for identifying and managing risks associated with conflict minerals (3TG: tin, tantalum, tungsten, gold).',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Malaysia is a major tin smelter. Describe due diligence per OECD Conflict Minerals Guidance. List certified smelters (RMAP). This is mandatory for Dodd-Frank Section 1502 compliance (US-listed suppliers).',
            'priority'     => 'critical',
            'financing_link' => 'Required for US public company supply chain compliance',
        ],
        [
            'indicator_id' => 'SASB-TECH-S03',
            'code'         => 'TC-HW-430b.1',
            'name'         => 'Supplier RBA Code Audit Rate',
            'description'  => '% of suppliers audited to RBA (Responsible Business Alliance) Code of Conduct or equivalent standard.',
            'unit'         => '%',
            'data_type'    => 'percentage',
            'required'     => true,
            'guidance'     => 'RBA is the standard for electronics supply chain. Count % of significant Tier 1 suppliers with RBA or equivalent audit (EICC, SMETA) in last 2 years. Apple requires 100% of strategic suppliers.',
            'priority'     => 'critical',
            'financing_link' => 'Apple, HP, Dell, Sony supplier compliance requirement',
        ],
        [
            'indicator_id' => 'SASB-TECH-S04',
            'code'         => 'TC-HW-330a.1',
            'name'         => 'Foreign Worker Management',
            'description'  => 'Description of practices for managing foreign (migrant) worker recruitment, housing, and rights.',
            'unit'         => null,
            'data_type'    => 'text',
            'required'     => true,
            'guidance'     => 'Malaysia electronics sector heavily relies on migrant workers. Describe: no fee recruitment policy (workers pay zero fees), passport non-retention, freedom of movement, decent housing. Key for Apple/Intel supplier approval.',
            'priority'     => 'critical',
            'financing_link' => 'UFLPA — US ban on goods with forced labour in supply chain',
        ],
    ],

    'GOVERNANCE' => [
        [
            'indicator_id' => 'SASB-TECH-G01',
            'code'         => 'TC-HW-520a.1',
            'name'         => 'Product Safety and Quality',
            'description'  => 'Number of recalls and percentage of revenue affected. Description of quality management system.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => true,
            'guidance'     => 'Report product recalls or customer quality issues. Describe ISO 9001 certification, IATF 16949 for automotive, quality management system, defect rate (DPPM).',
            'priority'     => 'high',
            'financing_link' => null,
        ],
        [
            'indicator_id' => 'SASB-TECH-G02',
            'code'         => 'TC-HW-230a.1',
            'name'         => 'Data Security — Customer Data Protection',
            'description'  => 'Number of data security breaches and customers affected.',
            'unit'         => 'incidents',
            'data_type'    => 'number',
            'required'     => false,
            'guidance'     => 'Relevant for companies handling customer data. Describe PDPA 2010 compliance, ISO 27001 certification, cybersecurity controls, and incident response plan.',
            'priority'     => 'medium',
            'financing_link' => null,
        ],
    ],
];
